#!/usr/bin/env Rscript


# suppressPackageStartupMessages(require(argparser))
# suppressPackageStartupMessages(require(glue))
# suppressPackageStartupMessages(require(rmarkdown))


p <- argparser::arg_parser(description = "Play with DRAGEN fire", name = "dracarys", hide.opts = TRUE)
p <- argparser::add_argument(p, arg = "--name", help = "name of sample")
p <- argparser::add_argument(p, arg = "--outdir", help = "output directory", default = "dracarys")
p <- argparser::add_argument(p, arg = "--indir", help = "input dir")

argv <- argparser::parse_args(p)

name <- argv$name
indir <- normalizePath(argv$indir)
if (!dir.exists(argv$outdir)) {
  dir.create(argv$outdir)
}
outdir <- normalizePath(argv$outdir)
tumor_normal_rmd <- system.file("rmd", "tumor_normal", "tumor_normal.Rmd", package = "dracarys")

cat(glue::glue("indir: {indir}"), sep = "\n")
cat(glue::glue("outdir: {outdir}"), sep = "\n")
cat(glue::glue("name: {name}"), sep = "\n")
cat(glue::glue("rmd: {tumor_normal_rmd}"))

params_list <- list(
  indir = indir,
  outdir = outdir,
  name = name
)

rmarkdown::render(input = tumor_normal_rmd,
                  output_file = paste0(name, "_dracarys.html"),
                  output_dir = outdir,
                  params = params_list)
