# Generated by roxytest: Do not edit by hand!

context("File R/dragen_version.R: @testexamples")

test_that("Function read_replay() @ L22", {
  
  x <- system.file("extdata/COLO829-replay.json.gz", package = "dracarys")
  (replay <- read_replay(x))
  
  expect_equal(names(replay), c("command_line", "dragen_config", "inputs", "system", "label"))
})

