# Generated by roxytest: Do not edit by hand!

context("File R/qc_coverage.R: @testexamples")

test_that("Function read_wgs_coverage_metrics() @ L26", {
  
  x <- system.file("extdata/COLO829.wgs_coverage_metrics_normal.csv.gz", package = "dracarys")
  y <- system.file("extdata/COLO829.wgs_coverage_metrics_tumor.csv.gz", package = "dracarys")
  
  (cm_x <- read_wgs_coverage_metrics(x))
  (cm_y <- read_wgs_coverage_metrics(y))
  
  expect_equal(colnames(cm_x), c("label", "var", "var_abbrev", "pct", "count"))
  expect_equal(colnames(cm_y), c("label", "var", "var_abbrev", "pct", "count"))
})


test_that("Function read_wgs_contig_coverage() @ L106", {
  
  x <- system.file("extdata/COLO829.wgs_contig_mean_cov_normal.csv.gz", package = "dracarys")
  y <- system.file("extdata/COLO829.wgs_contig_mean_cov_tumor.csv.gz", package = "dracarys")
  
  (cc_x <- read_wgs_contig_coverage(x))
  (cc_y <- read_wgs_contig_coverage(y))
  
  expect_equal(colnames(cc_x), c("label", "chrom", "n_bases", "coverage"))
  expect_equal(colnames(cc_y), c("label", "chrom", "n_bases", "coverage"))
})


test_that("Function read_wgs_fine_hist() @ L240", {
  
  x <- system.file("extdata/COLO829.wgs_fine_hist_normal.csv.gz", package = "dracarys")
  y <- system.file("extdata/COLO829.wgs_fine_hist_tumor.csv.gz", package = "dracarys")
  
  (fh_x <- read_wgs_fine_hist(x))
  (fh_y <- read_wgs_fine_hist(y))
  
  expect_equal(colnames(fh_x), c("label", "depth", "n_loci"))
  expect_equal(colnames(fh_y), c("label", "depth", "n_loci"))
})

