# Generated by roxytest: Do not edit by hand!
# Last updated: 2020-03-23 22:28:35

context("File R/qc_runtime_metrics.R: @testexamples")

test_that("Function read_time_metrics() @ L19", {
  
  x <- system.file("extdata/COLO829.time_metrics.csv.gz", package = "dracarys")
  (tm <- read_time_metrics(x))
  
  expect_equal(colnames(tm), c("Label", "Step", "Time"))
})

