# Generated by roxytest: Do not edit by hand!

context("File R/qc_mapping_metrics.R: @testexamples")

test_that("Function read_mapping_metrics() @ L29", {
  
  x <- system.file("extdata/COLO829.mapping_metrics.csv.gz", package = "dracarys")
  (mm <- read_mapping_metrics(x))
  
  expect_equal(colnames(mm), c("category", "Phenotype", "RG", "var", "var_abbrev", "count", "pct"))
})

