# Generated by roxytest: Do not edit by hand!
# Last updated: 2020-03-31 19:16:47

context("File R/snv.R: @testexamples")

test_that("Function snv_table() @ L24", {
  
  conda_env_path <- "~/my_apps/miniconda/envs/dracarys/bin"
  x <- system.file("extdata/COLO829.hard-filtered.vcf.gz", package = "dracarys")
  (snvs <- snv_table(x, prefix = "COLO829", outdir = "out1", conda_env_path = conda_env_path))
  
  expect_equal(length(snvs), 2)
  expect_equal(names(snvs), c("variants", "samples"))
  expect_true(inherits(snvs$variants, "tbl_df"))
})

