# Generated by roxytest: Do not edit by hand!

context("File R/qc_runtime_metrics.R: @testexamples")

test_that("Function read_time_metrics() @ L19", {
  
  x <- system.file("extdata/COLO829.time_metrics.csv.gz", package = "dracarys")
  (tm <- read_time_metrics(x))
  
  expect_equal(colnames(tm), c("Label", "Step", "Time"))
})


test_that("Function time_metrics_process() @ L53", {
  
  x <- system.file("extdata/COLO829.time_metrics.csv.gz", package = "dracarys")
  (tm <- time_metrics_process(c(x, x), id = c("run1", "run2")))
  
  expect_equal(nrow(tm), 2)
})

