# Generated by roxytest: Do not edit by hand!
# Last updated: 2020-03-23 22:28:35

context("File R/qc_varcalling_metrics.R: @testexamples")

test_that("Function read_varcalling_metrics() @ L29", {
  
  x <- system.file("extdata/COLO829.vc_metrics.csv.gz", package = "dracarys")
  (vm <- read_varcalling_metrics(x))
  
  expect_equal(colnames(vm), c("category", "sample", "var", "count", "pct"))
})

