# Generated by roxytest: Do not edit by hand!

context("File R/qc_fragment_length.R: @testexamples")

test_that("Function read_fragment_length_hist() @ L20", {
  
  x <- system.file("extdata/Colo829.fragment_length_hist.csv.gz", package = "dracarys")
  (fl <- read_fragment_length_hist(x))
  
  expect_equal(colnames(fl), c("fragmentLength", "count", "sample"))
})

