# Generated by roxytest: Do not edit by hand!

context("File R/setup_vars.R: @testexamples")

test_that("Function setup_vars() @ L24", {
  
  x <- system.file("extdata/COLO829-replay.json.gz", package = "dracarys")
  (v <- setup_vars(x))
  
  expect_equal(class(v), "list")
  expect_equal(length(v), 1)
  expect_equal(length(v[[1]]), 14)
  expect_equal(names(v[[1]]), c("name", "res_dir", "replay_fn", "fraglen_fn", "map_met_fn",
  "ploidy_est_fn", "time_met_fn", "cov_contig_fn", "cov_met_fn",
  "cov_finehist_fn", "vc_met_fn", "snv_fn", "sv_fn", "steps_run"))
})

