---
author: "University of Melbourne Centre for Cancer Research"
date: "`r format(Sys.time(), '%a %Y-%b-%d %H:%M')`"
output:
  html_document:
    theme: flatly # cosmo # simplex
    toc: false
    code_download: true
    css: style.css
  rmdformats::material:
    highlight: kate
params:
  res_dir: "/path/to/dragen/results"
  nm: "COLO829"
title: "`r glue::glue('DRAGEN Tumor-Normal Results for {params$nm}')`"
description: "Results from DRAGEN tumor-normal analysis"
---

<style type="text/css">
.main-container {
  max-width: 2000px;
  margin-left: auto;
  margin-right: auto;
}
</style>


```{r load_knitr, include=F}
require(knitr)
knitr::opts_chunk$set(
  echo = FALSE
)
```

```{r render_report_interactively, eval=F, echo=F}
params <- function(x) {
  paths <- list(
    local = list(
      res_dir = here::here("nogit/SBJ00238"),
      nm = "SBJ00238")
  )
  paths[[x]]
}
params <- params("local")

render_me <- function() {
  rmarkdown::render(
    input = here::here("inst/rmd/tumor_normal.Rmd"),
    params = params)
}
render_me()
```

```{r load_pkgs, message=F, warning=F}
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(dracarys))
suppressPackageStartupMessages(library(DT))
suppressPackageStartupMessages(library(glue))
suppressPackageStartupMessages(library(jsonlite))
suppressPackageStartupMessages(library(kableExtra))
suppressPackageStartupMessages(library(purrr))
suppressPackageStartupMessages(library(readr))
suppressPackageStartupMessages(library(tidyr))
```

```{r var_setup}
nm <- params$nm
res_dir <- params$res_dir
lab_tumor <- "tumor"
lab_normal <- "normal"

replay <- glue::glue("{res_dir}/{nm}-replay.json") %>% dracarys::read_replay()
dragen_config <- replay$dragen_config
eval_steps <- list(
  run_sv = dplyr::filter(replay$dragen_config, grepl("^enable-sv$", name)) %>%
    dplyr::pull(value) %>% toupper() %>% as.logical(),
  run_varcall = dplyr::filter(replay$dragen_config, grepl("^enable-variant-caller$", name)) %>%
    dplyr::pull(value) %>% toupper() %>% as.logical()
)
```

### QC {.tabset .tabset-fade #qc}

#### Timing
```{r qc_time_metrics}
time_metrics <- glue::glue("{res_dir}/{nm}.time_metrics.csv") %>%
  dracarys::read_time_metrics()

time_metrics %>%
  knitr::kable(format = "html", col.names = NULL) %>%
  kableExtra::kable_styling(full_width = FALSE, position = "left",
                            bootstrap_options = c("striped", "bordered",
                                                  "condensed", "hover")) %>%
  kableExtra::column_spec(1, bold = TRUE) %>%
  kableExtra::row_spec(nrow(time_metrics), bold = T,
                       color = "white", background = "#2c3e50")
```

#### Coverage Plots
```{r qc_cov_contig_plot, fig.height=3.5}
cov_contig_normal <- glue::glue("{res_dir}/{nm}.wgs_contig_mean_cov_{lab_normal}.csv")
cov_contig_tumor <- glue::glue("{res_dir}/{nm}.wgs_contig_mean_cov_{lab_tumor}.csv")
plot_wgs_contig_coverage(tumor = cov_contig_tumor, normal = cov_contig_normal)
```

```{r qc_cov_wgs_fine_hist, fig.height=3.5}
cov_fine_normal <- glue::glue("{res_dir}/{nm}.wgs_fine_hist_{lab_normal}.csv")
cov_fine_tumor <- glue::glue("{res_dir}/{nm}.wgs_fine_hist_{lab_tumor}.csv")
plot_wgs_fine_hist(tumor = cov_fine_tumor, normal = cov_fine_normal)
```

#### Coverage Metrics
```{r qc_cov_metrics}
cov_metrics_tumor <-
  glue::glue("{res_dir}/{nm}.wgs_coverage_metrics_{lab_tumor}.csv") %>%
  dracarys::read_wgs_coverage_metrics(label = lab_tumor)
cov_metrics_normal <-
  glue::glue("{res_dir}/{nm}.wgs_coverage_metrics_{lab_normal}.csv") %>%
  dracarys::read_wgs_coverage_metrics(label = lab_normal)

cov_metrics <- dplyr::bind_rows(cov_metrics_tumor, cov_metrics_normal)
```

```{r qc_cov_metrics_count}
cov_metrics_count <- cov_metrics %>%
  tidyr::pivot_wider(id_cols = label,
                     names_from = var_abbrev,
                     values_from = count) %>%
  dplyr::select_if(colSums(!is.na(.)) > 0)

cov_metrics_count %>%
  DT::datatable(rownames = FALSE,
                # callback = JS(glue::glue("
                #   var tips = {tab_descr};
                #   var header = table.columns().header();
                #   for (var i = 0; i < tips.length; i++) {{
                #     $(header[i]).attr('title', tips[i]);
                #   }}")),
                caption = "Counts",
                class = "cell-border display compact",
                extensions = c("Scroller", "KeyTable"),
                options = list(
                  scroller = TRUE, scrollY = 150, keys = TRUE, dom = 'lfrtip')) %>%
  DT::formatCurrency(colnames(cov_metrics_count),
                     currency = "", interval = 3, mark = ",", digits = 0)
```

```{r qc_cov_metrics_pct}
cov_metrics_pct <- cov_metrics %>%
  tidyr::pivot_wider(id_cols = label,
                     names_from = var_abbrev,
                     values_from = pct) %>%
  dplyr::select_if(colSums(!is.na(.)) > 0)

cov_metrics_pct %>%
  DT::datatable(rownames = FALSE,
                # callback = JS(glue::glue("
                #   var tips = {tab_descr};
                #   var header = table.columns().header();
                #   for (var i = 0; i < tips.length; i++) {{
                #     $(header[i]).attr('title', tips[i]);
                #   }}")),
                caption = "Percentages",
                class = "cell-border display compact",
                extensions = c("Scroller", "KeyTable"),
                options = list(
                  scroller = TRUE, scrollY = 150,
                  keys = TRUE, dom = 'lfrtip'))
```

#### Ploidy Estimation
```{r qc_ploidy_estimation_tab}
ploidy_estimation <- dracarys::read_ploidy_estimation_metrics(glue::glue("{res_dir}/{nm}.ploidy_estimation_metrics.csv"))
ploidy_estimation %>%
knitr::kable(format = "html", col.names = NULL) %>%
  kableExtra::kable_styling(full_width = FALSE, position = "left",
                            bootstrap_options = c("striped", "bordered",
                                                  "condensed", "hover")) %>%
  kableExtra::column_spec(1, bold = TRUE)

```

#### Mapping Metrics
```{r qc_map_metrics_tab}
mapping_metrics <- dracarys::read_mapping_metrics(glue::glue("{res_dir}/{nm}.mapping_metrics.csv"))
mapping_metrics <- list(
  data = mapping_metrics,
  abbrev = dplyr::distinct(mapping_metrics, var, var_abbrev),
  count = tidyr::pivot_wider(
    mapping_metrics, id_cols = c(Phenotype, RG),
    names_from = var_abbrev, values_from = count),
  pct = tidyr::pivot_wider(
    mapping_metrics, id_cols = c(Phenotype, RG),
    names_from = var_abbrev, values_from = pct)
)

mma <- mapping_metrics$abbrev
```

```{r qc_map_metrics_tab_pct}
dpct <- mapping_metrics$pct %>%
  dplyr::select_if(colSums(!is.na(.)) > 0)
tab_descr <- mma$var[match(colnames(dpct), mma$var_abbrev)] %>%
  jsonlite::toJSON()

dpct %>%
  DT::datatable(rownames = FALSE,
                callback = JS(glue::glue("
                  var tips = {tab_descr};
                  var header = table.columns().header();
                  for (var i = 0; i < tips.length; i++) {{
                    $(header[i]).attr('title', tips[i]);
                  }}")),
                caption = "Percentages. Bar range: 90-100",
                class = "cell-border display compact",
                extensions = c("Scroller", "KeyTable"),
                options = list(
                  scroller = TRUE, scrollY = 150, scrollX = TRUE,
                  autoWidth = TRUE, keys = TRUE, dom = 'lfrtip')) %>%
  DT::formatStyle(colnames(dpct),
                  background = DT::styleColorBar(c(90, 100), color = "lightblue"),
                  backgroundSize = "90% 90%", backgroundRepeat = 'no-repeat',
                  backgroundPosition = 'center')
```

```{r qc_map_metrics_tab_count}
dcount <- mapping_metrics$count %>%
  dplyr::select_if(colSums(!is.na(.)) > 0)
tab_descr <- mma$var[match(colnames(dcount), mma$var_abbrev)] %>%
  jsonlite::toJSON()

dcount %>%
  DT::datatable(rownames = FALSE,
                callback = JS(glue::glue("
                  var tips = {tab_descr};
                  var header = table.columns().header();
                  for (var i = 0; i < tips.length; i++) {{
                    $(header[i]).attr('title', tips[i]);
                  }}")),
                caption = "Counts.",
                class = "cell-border display compact",
                extensions = c("Scroller", "KeyTable"),
                options = list(
                  scroller = TRUE, scrollY = 150, scrollX = TRUE,
                  autoWidth = TRUE, keys = TRUE, dom = 'lfrtip')) %>%
  DT::formatCurrency(colnames(dcount),
                     currency = "", interval = 3, mark = ",", digits = 0)
```


#### VarCalling Metrics
```{r qc_vc_metrics_tab, eval=eval_steps$run_varcall}
vc_metrics <- read_varcalling_metrics(glue::glue("{res_dir}/{nm}.vc_metrics.csv")) %>%
  dplyr::filter(category != "summary")
vc_metrics <- list(
  data = vc_metrics,
  count = tidyr::pivot_wider(
    vc_metrics, id_cols = c(category, sample),
    names_from = var, values_from = count),
  pct = tidyr::pivot_wider(
    vc_metrics, id_cols = c(category, sample),
    names_from = var, values_from = pct)
)
```

```{r qc_vc_metrics_tab_count, eval=eval_steps$run_varcall}
dcount <- vc_metrics$count %>%
  dplyr::select_if(colSums(!is.na(.)) > 0)
# tab_descr <- mma$var[match(colnames(dcount), mma$var_abbrev)] %>%
#   jsonlite::toJSON()

dcount %>%
  DT::datatable(rownames = FALSE,
                # callback = JS(glue::glue("
                #   var tips = {tab_descr};
                #   var header = table.columns().header();
                #   for (var i = 0; i < tips.length; i++) {{
                #     $(header[i]).attr('title', tips[i]);
                #   }}")),
                caption = "Counts.",
                class = "cell-border display compact",
                extensions = c("Scroller", "KeyTable"),
                options = list(
                  scroller = TRUE, scrollY = 150, scrollX = TRUE,
                  autoWidth = TRUE, keys = TRUE, dom = 'lfrtip')) %>%
  DT::formatCurrency(colnames(dcount),
                     currency = "", interval = 3, mark = ",", digits = 0)
```

```{r qc_vc_metrics_tab_pct, eval=eval_steps$run_varcall}
dpct <- vc_metrics$pct %>%
  dplyr::select_if(colSums(!is.na(.)) > 0)
# tab_descr <- mma$var[match(colnames(dpct), mma$var_abbrev)] %>%
#   jsonlite::toJSON()

dpct %>%
  DT::datatable(rownames = FALSE,
                # callback = JS(glue::glue("
                #   var tips = {tab_descr};
                #   var header = table.columns().header();
                #   for (var i = 0; i < tips.length; i++) {{
                #     $(header[i]).attr('title', tips[i]);
                #   }}")),
                caption = "Percentages. Bar range: 90-100",
                class = "cell-border display compact",
                extensions = c("Scroller", "KeyTable"),
                options = list(
                  scroller = TRUE, scrollY = 150,
                  autoWidth = TRUE, keys = TRUE, dom = 'lfrtip')) %>%
  DT::formatStyle(colnames(dpct),
                  background = DT::styleColorBar(c(90, 100), color = "lightblue"),
                  backgroundSize = "90% 90%", backgroundRepeat = 'no-repeat',
                  backgroundPosition = 'center')
```

#### Fragment Length Distribution
```{r qc_frag_len_distr, fig.height=3.5}
dracarys::plot_fragment_length_hist(glue::glue("{res_dir}/{nm}.fragment_length_hist.csv"))
```

## Addendum {.tabset .tabset-fade #addendum}

### DRAGEN {.tabset .tabset-fade}

#### Version
```{r dragen_replay_system}
replay$system %>%
  knitr::kable(format = "html", col.names = NULL) %>%
  kableExtra::kable_styling(full_width = FALSE, position = "left",
                            bootstrap_options = c("striped", "bordered",
                                                  "condensed", "hover")) %>%
  kableExtra::column_spec(1, bold = TRUE)
```

#### Parameters
```{r dragen_replay_config}
replay$dragen_config %>%
  knitr::kable(format = "html") %>%
  kableExtra::kable_styling(full_width = FALSE, position = "left",
                            bootstrap_options = c("striped", "bordered",
                                                  "condensed", "hover")) %>%
  kableExtra::scroll_box(height = "200px")
```

### Report Inputs
```{r report_inputs, eval=T}
dplyr::tibble(name = names(params), value = unlist(params)) %>%
  knitr::kable(format = "html") %>%
  kableExtra::kable_styling(full_width = FALSE, position = "left",
                            bootstrap_options = c("striped", "bordered",
                                                  "condensed", "hover")) %>%
  kableExtra::column_spec(1, bold = TRUE)
```

### R Session Info
```{r session_info, eval=T}
si <- devtools::session_info(include_base = TRUE)
unclass(si$packages) %>%
  dplyr::as_tibble() %>%
  dplyr::mutate(main_pkgs = ifelse(package %in% c("woofr", "rock", "base"), "A", "B")) %>%
  dplyr::arrange(main_pkgs, package) %>%
  dplyr::select(package, version = ondiskversion, path, datestamp = date) %>%
  knitr::kable(format = "html") %>%
  kableExtra::kable_styling(full_width = FALSE, position = "left",
                            bootstrap_options = c("striped", "bordered",
                                                  "condensed", "hover")) %>%
  kableExtra::column_spec(1, bold = TRUE) %>%
  kableExtra::scroll_box(height = "200px")
```

***

<p>&nbsp;</p>
